import navCategories from "./data/nav-categories.json";

/**
 * Tiny category + subcategory-name summary for the site nav's mega menu.
 * Deliberately separate from `lib/catalogue.ts` (whose product index is
 * ~1MB) — <Nav> renders on every page, so it must not bundle the full
 * catalogue just to show a dropdown. Regenerated by
 * `scripts/import-pricelist.py` alongside the rest of the catalogue data.
 */
export type NavCategory = {
  key: string;
  slug: string;
  cls: string;
  icon: string;
  subcats: string[];
};

export const NAV_CATEGORIES: NavCategory[] = navCategories;
